"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "CSV to JSON Converter",
//   description: "Generated by SK MAIDUL ISLAM Using Next.js",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        ></link>
        <title>CSV to JSON Converter</title>
      </head>
      <body className={inter.className}>
        <ChakraProvider>{children}</ChakraProvider>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}
